package com.example.androidproject.adapters;

import android.text.Layout;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;

import androidx.annotation.NonNull;
import androidx.recyclerview.widget.DiffUtil;
import androidx.recyclerview.widget.ListAdapter;
import androidx.recyclerview.widget.RecyclerView;

import com.example.androidproject.databinding.ShopRowBinding;
import com.example.androidproject.models.Product;

public class ShopListAdapter extends ListAdapter<Product, ShopListAdapter.ShopViewHolder> {

    ShopInterface shopInterface;

    public ShopListAdapter(ShopInterface shopInterface) {
        super(Product.itemCallback);
        this.shopInterface = shopInterface;

    }

    //We inflate the shop view holder
    @NonNull
    @Override
    public ShopViewHolder onCreateViewHolder(@NonNull ViewGroup parent, int viewType) {
        LayoutInflater layoutInflater = LayoutInflater.from(parent.getContext());
        ShopRowBinding shopRowBinding = ShopRowBinding.inflate(layoutInflater, parent, false);
        shopRowBinding.setShopInterface(shopInterface);  //Has been automatically created in XML
        return new ShopViewHolder(shopRowBinding);
    }

    //The method setProduct is automaticcaly generated by databindinding in "shop row.xml"
    @Override
    public void onBindViewHolder(@NonNull ShopViewHolder holder, int position) {
        Product product = getItem(position);
        holder.shopRowBinding.setProduct(product);
     //   holder.shopRowBinding.executePendingBindings();

    }

    class ShopViewHolder extends RecyclerView.ViewHolder{
        ShopRowBinding shopRowBinding;

        public ShopViewHolder(ShopRowBinding binding) {
            super(binding.getRoot());
            this.shopRowBinding = binding;
        }
    }

    //We make this interface so it can handle the events of adding an item to the cart, or going to product detail fragment
    public interface ShopInterface {
        void addItem(Product product);
        void onItemClick(Product product);
    }
}
